# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, os

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 450)
        Dialog.setMinimumSize(QtCore.QSize(500, 450))
        Dialog.setMaximumSize(QtCore.QSize(500, 450))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 162, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 190, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.id_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.id_lineEdit.setGeometry(QtCore.QRect(172, 160, 131, 21))
        self.id_lineEdit.setObjectName("id_lineEdit")
        self.pw_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.pw_lineEdit.setGeometry(QtCore.QRect(172, 190, 131, 21))
        self.pw_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pw_lineEdit.setObjectName("pw_lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 160, 93, 51))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 500, 450))
        self.widget.setMinimumSize(QtCore.QSize(500, 450))
        self.widget.setMaximumSize(QtCore.QSize(500, 450))
        self.widget.setObjectName("widget")
        self.pwd_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.pwd_lineEdit.setGeometry(QtCore.QRect(170, 342, 131, 21))
        self.pwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_lineEdit.setObjectName("pwd_lineEdit")
        self.pw2_pushButton = QtWidgets.QPushButton(Dialog)
        self.pw2_pushButton.setGeometry(QtCore.QRect(310, 340, 91, 61))
        self.pw2_pushButton.setText("")
        self.pw2_pushButton.setObjectName("pw2_pushButton")
        self.pw2set_pushButton = QtWidgets.QPushButton(Dialog)
        self.pw2set_pushButton.setGeometry(QtCore.QRect(170, 372, 131, 28))
        self.pw2set_pushButton.setText("")
        self.pw2set_pushButton.setObjectName("pw2set_pushButton")
        self.widget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.id_lineEdit.raise_()
        self.pw_lineEdit.raise_()
        self.pushButton.raise_()
        self.pwd_lineEdit.raise_()
        self.pw2_pushButton.raise_()
        self.pw2set_pushButton.raise_()

        root_path = getattr(sys, '_MEIPASS')
        print('root_path: ', root_path)

        self.widget.setStyleSheet('image:url(' + os.path.join(root_path, 'login.png') + ');border:0px;')
        self.pushButton.setStyleSheet(
            '''
                QPushButton{image:url(''' + os.path.join(root_path, 'ok1.png') + ''');border:0px;}
            ''')
        self.pw2_pushButton.setStyleSheet(
            '''
                QPushButton{image:url(''' + os.path.join(root_path, 'ok2.png') + ''');border:0px;}
            ''')
        self.pw2set_pushButton.setStyleSheet(
            '''
                QPushButton{image:url(''' + os.path.join(root_path, 'pwset.png') + ''');border:0px;}
            ''')
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
