# Generated by Django 3.0.6 on 2020-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HideList',
            fields=[
                ('index', models.IntegerField(db_column='INDEX', primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_column='FILE_PATH', max_length=200)),
                ('state', models.BooleanField(db_column='STATE')),
                ('priority', models.IntegerField(db_column='PRIORITY')),
            ],
        ),
    ]
