# Generated by Django 3.0.6 on 2020-05-22 08:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hide', '0003_auto_20200522_1532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myfile',
            unique_together={('index', 'author')},
        ),
    ]
