# Generated by Django 3.0.6 on 2020-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hide', '0009_auto_20200522_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='index',
            field=models.IntegerField(db_column='INDEX'),
        ),
    ]
