# Generated by Django 3.0.6 on 2020-05-22 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hide', '0002_hidelist_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfile',
            fields=[
                ('index', models.IntegerField(db_column='INDEX', primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_column='FILE_PATH', max_length=200)),
                ('state', models.BooleanField(db_column='STATE')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HideList',
        ),
    ]
