# Generated by Django 3.0.6 on 2020-05-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hide', '0006_auto_20200522_1737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myfile',
            unique_together=set(),
        ),
    ]
