# Generated by Django 3.0.6 on 2020-05-25 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('hide', '0010_auto_20200522_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkState',
            fields=[
                ('network_state', models.BooleanField(db_column='NETWORK_STATE')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
