# Generated by Django 3.0.6 on 2020-05-25 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hide', '0012_auto_20200525_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkstate',
            name='id',
        ),
        migrations.AlterField(
            model_name='networkstate',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
