# Generated by Django 3.0.6 on 2020-05-25 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hide', '0013_auto_20200525_1840'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myfile',
            unique_together={('author', 'file_path')},
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='index',
        ),
    ]
